name: Android Lint Flow
run-name: Running Lint Check - ${{ github.event_name }}

on:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - 'master'

jobs:
  android-lint:
    runs-on: ubuntu-latest

    #To Checkout Repository
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      #To Set up JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      #To Grant Execute Permission to Gradle
      - name: Grant Execute Permission to Gradle
        run: chmod +x ./gradlew

      #To Run Android Lint
      - name: Run Android Lint
        run: ./gradlew lintDebug
        continue-on-error: false


      #To Validate Lint Report Exists
      - name: Validate Lint Report Exists
        run: |
          if [ ! -f app/build/reports/lint-results-debug.html ]; then
            echo "❌ Lint report not found!"
            exit 1
          fi

      #To Upload Lint Report
      - name: Upload Lint Report
        uses: actions/upload-artifact@v4
        with:
          name: lint-report
          path: app/build/reports/lint-results-debug.html

