name: Test Case WorkFlow
run-name: Running UnitTest - ${{ github.event_name }}

on:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - 'master'

jobs:
  run-unit-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: gradle

      - name: Grant Execute Permission to Gradle
        run: chmod +x ./gradlew

      - name: Run Unit Tests
        run: ./gradlew testDebugUnitTest

      - name: Validate Test Report Exists
        run: |
          if [ ! -f app/build/reports/tests/testDebugUnitTest/index.html ]; then
            echo "Test report not found!"
            exit 1
          fi


      - name: Upload Test Report
        uses: actions/upload-artifact@v4
        with:
          name: unit-test-report
          path: app/build/reports/tests/testDebugUnitTest/index.html
